###
# Set origins appropriately, is follows standard action cable format for allowed_request_origins
###
production:
  ##TODO edit me
  allowed_request_origins: http://127.0.0.1:3000/cable_x
development:
  allowed_request_origins: http://127.0.0.1:3000/cable_x
test:
  allowed_request_origins: http://127.0.0.1:3000/cable_x